import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import { loadFacts, repoPath } from "./content-utils";

/**
 * Виводить унікальні URL із sources[] у фактах у markdown-файл,
 * який потім споживає lychee у CI (link-check.yml).
 *
 * Дефолтне розташування: dist/.fact-source-urls.md (поза svn/git-tracked
 * деревом, у тій же теці, що й білд).
 */
const outPath = process.argv[2] ?? repoPath("dist", ".fact-source-urls.md");

const facts = await loadFacts();

const seen = new Map<string, string[]>();
for (const fact of facts) {
  const relativePath = path.relative(process.cwd(), fact.filePath);
  for (const source of fact.sources) {
    const list = seen.get(source.url) ?? [];
    list.push(relativePath);
    seen.set(source.url, list);
  }
}

const sortedUrls = [...seen.keys()].sort((a, b) => a.localeCompare(b));

const lines = [
  "# Fact source URLs",
  "",
  `Generated by \`scripts/dump-source-urls.ts\` from ${facts.length} facts.`,
  "",
  ...sortedUrls.map((url) => `- <${url}>`),
  "",
];

await mkdir(path.dirname(outPath), { recursive: true });
await writeFile(outPath, lines.join("\n"), "utf8");

console.log(
  `Wrote ${sortedUrls.length} unique source URLs from ${facts.length} facts → ${outPath}`,
);
