/**
 * Build-time service-worker generator.
 *
 * Runs after `astro build` (and `pagefind --site dist`) finishes, scans
 * `dist/` for assets, decides which go into precache vs runtime cache,
 * computes a content-addressed cache version, and writes a vanilla
 * `dist/sw.js`. No Workbox: the surface area we need (cache-first for
 * static, network-first for navigation, offline fallback) fits in ~100
 * lines, and skipping Workbox saves the dep + the build step.
 *
 * Invoked via `npm run build` (see `package.json`).
 */
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { categorizeAsset, computeCacheVersion, toUrlPath } from "../src/lib/swUtils";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const DIST_DIR = join(REPO_ROOT, "dist");
const OFFLINE_URL = "/offline/";
const SW_OUTPUT = join(DIST_DIR, "sw.js");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(abs));
    } else if (entry.isFile()) {
      out.push(abs);
    }
  }
  return out;
}

function shortHash(absPath: string): string {
  // Short content hash is enough — we already mix in the URL when computing
  // the global cache version, so collisions are essentially impossible.
  const h = createHash("sha256");
  h.update(readFileSync(absPath));
  return h.digest("hex").slice(0, 16);
}

function bucketAssets(dist: string): {
  precache: { url: string; hash: string }[];
  hasOffline: boolean;
  htmlSample: number;
} {
  if (!existsSync(dist)) {
    throw new Error(`[generate-sw] dist/ not found at ${dist}; did the build run?`);
  }
  const files = walk(dist).map((abs) => ({
    abs,
    rel: relative(dist, abs).split(/\\|\//).join("/"),
  }));
  const precache: { url: string; hash: string }[] = [];
  let htmlSample = 0;
  let hasOffline = false;
  const seen = new Set<string>();
  for (const file of files) {
    if (file.rel === "sw.js") continue;
    const url = toUrlPath(file.rel);
    if (seen.has(url)) continue;
    seen.add(url);
    const bucket = categorizeAsset(url);
    if (bucket === "precache") {
      precache.push({ url, hash: shortHash(file.abs) });
    } else if (bucket === "runtime") {
      htmlSample += 1;
      if (url === OFFLINE_URL) hasOffline = true;
    }
  }
  // Mirror precache list into a stable order so two runs over the same
  // dist tree produce identical sw.js bytes (helps Vercel/Netlify cache).
  precache.sort((a, b) => a.url.localeCompare(b.url));
  return { precache, hasOffline, htmlSample };
}

function buildSwSource(precache: { url: string; hash: string }[], version: string): string {
  const precacheList = JSON.stringify(precache.map((p) => p.url));
  // Service-worker source. Vanilla — no imports, no module syntax — so
  // browsers without `type: 'module'` SW support still pick it up.
  return `/* AUTOGENERATED by scripts/generate-sw.ts. Do not edit by hand. */
/* eslint-disable */
const VERSION = ${JSON.stringify(version)};
const PRECACHE = "back-future-precache-" + VERSION;
const RUNTIME = "back-future-runtime-" + VERSION;
const OFFLINE_URL = ${JSON.stringify(OFFLINE_URL)};
const PRECACHE_URLS = ${precacheList};
const NETWORK_TIMEOUT_MS = 4000;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE);
      // \`{ cache: "reload" }\` bypasses the HTTP cache so a stale CDN copy of
      // a renamed hashed asset can't slip into the SW precache.
      const requests = PRECACHE_URLS.concat([OFFLINE_URL]).map(
        (u) => new Request(u, { cache: "reload" }),
      );
      await Promise.all(
        requests.map((req) =>
          cache.add(req).catch(() => {
            // Single asset failing should never block install — the runtime
            // fetch handler will simply hit the network for that URL.
          }),
        ),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((k) => k !== PRECACHE && k !== RUNTIME)
          .filter((k) => k.startsWith("back-future-"))
          .map((k) => caches.delete(k)),
      );
      // Take control of any open clients so the first visit after install
      // gets the offline experience without an extra full reload.
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

function isNavigation(request) {
  if (request.mode === "navigate") return true;
  return request.method === "GET" && (request.headers.get("accept") || "").includes("text/html");
}

async function networkFirst(request) {
  const cache = await caches.open(RUNTIME);
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), NETWORK_TIMEOUT_MS);
    const response = await fetch(request, { signal: controller.signal });
    clearTimeout(timeout);
    if (response && response.ok) {
      cache.put(request, response.clone()).catch(() => {});
    }
    return response;
  } catch (err) {
    const cached = await caches.match(request);
    if (cached) return cached;
    const offline = await caches.match(OFFLINE_URL);
    if (offline) return offline;
    throw err;
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response && response.ok && response.type !== "opaque") {
      const cache = await caches.open(RUNTIME);
      cache.put(request, response.clone()).catch(() => {});
    }
    return response;
  } catch (err) {
    throw err;
  }
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  // Skip the SW + manifest themselves and anything under /pagefind/ — that
  // bundle ships its own integrity checks and is lazy-loaded by the search UI.
  if (url.pathname === "/sw.js" || url.pathname === "/manifest.webmanifest") return;
  if (url.pathname.startsWith("/pagefind/")) return;
  if (isNavigation(request)) {
    event.respondWith(networkFirst(request));
    return;
  }
  // Same-origin static asset. We don't try to detect which bucket it lives in
  // (the precache decision was made at build time); a generic cache-first
  // with runtime backfill is enough.
  event.respondWith(cacheFirst(request));
});
`;
}

function main(): void {
  const { precache, hasOffline, htmlSample } = bucketAssets(DIST_DIR);
  if (!hasOffline) {
    throw new Error(
      "[generate-sw] expected " +
        OFFLINE_URL +
        " in dist/. Did src/pages/offline.astro get pruned?",
    );
  }
  const version = computeCacheVersion(precache);
  const sw = buildSwSource(precache, version);
  writeFileSync(SW_OUTPUT, sw);
  console.log(
    `[generate-sw] wrote ${relative(REPO_ROOT, SW_OUTPUT)} ` +
      `(version=${version}, precache=${precache.length}, html=${htmlSample})`,
  );
}

main();
